name: CC-Essentials
main: fr.cartooncraft.essentials.CCEssentials
version: 0.1
commands:
    list:
        description: Return players list.
        usage: /list
    spawn:
        description: Teleport you to spawn. 
        usage: /spawn
    tp:
        description: Teleports you to another player, or teleport a player to another.
        usage: /tp <player> | /tp <player1> <player2> | /tp <x> <y> <z> | /tp <player> <x> <y> <z>
    kill:
        description: Kill yourself or a player
        usage: /kill [player]
    broadcast:
        description: ...
        usage: /broadcast <msg>
    tell:
        description: Send a message to another guy.
        usage: /tell <player> <msg>
    whisp:
        description: Send a message to another guy.
        usage: /whisp <player> <msg>
    whisper:
        description: Send a message to another guy.
        usage: /whisper <player> <msg>
    t:
        description: Send a message to another guy.
        usage: /t <player> <msg>
    w:
        description: Send a message to another guy.
        usage: /w <player> <msg>
    pm:
        description: Send a message to another guy.
        usage: /pm <player> <msg>
    mp:
        description: Send a message to another guy.
        usage: /mp <player> <msg>
    msg:
        description: Send a message to another guy.
        usage: /msg <player> <msg>
    kick:
        description: Kick a player with reason.
        usage: /kick <player> [reason]